thunderstore-io/Thunderstore

django/repository/views.py
=> Fix ordering of package list so pinned items are first

builder/src/scss/theme/_bootswatch.scss, django/frontend/templates/base.html
https://funkfrog.me/8Mv3t8bsLq.gif
=> Replace API Link with 'Developers' Dropdown

.github/workflows/docker-build.yml
Add a GitHub action for building the Docker image
=> Add a GitHub action for building the Docker Image

.github/workflows/docker-build.yml
Add a test running stage to the github CI workflow
=> Run tests on the CI pipeline

django/thunderstore/repository/package_reference.py, django/thunderstore/repository/package_upload.py
=> Replace Union[None] with Optional[]

django/backblaze_b2/storage.py, django/thunderstore/core/cache.py, django/thunderstore/repository/package_upload.py, django/thunderstore/repository/views.py
=> Replace super(...) with super()

Dockerfile
=> Re-order Dockerfile layer

django/thunderstore/repository/migrations/0023_add_display_name.py, django/thunderstore/repository/models/package.py, django/thunderstore/repository/models/package_version.py
Tested the migration from 0022
=> Fix display name

.github/workflows/test.yml
Not sure if "missing migrations" is the best name
=> Add missing migrations check

django/conftest.py, django/thunderstore/repository/models/uploader_identity.py, django/thunderstore/repository/package_manifest.py, django/thunderstore/repository/package_upload.py, django/thunderstore/repository/serializer_fields.py, django/thunderstore/repository/templates/repository/package_create.html, django/thunderstore/repository/tests/test_package_manifest.py, django/thunderstore/repository/tests/test_package_upload.py, django/thunderstore/repository/tests/test_uploader_identity.py, django/thunderstore/repository/views.py
=> Add author_name field to manifest

.github/workflows/release.yml, .github/workflows/test.yml
[Example](https://github.com/risk-of-thunder/Thunderstore/pull/198/checks?check_run_id=1634931439#step:10:5)
=> Add logs when pushing docker images

django/thunderstore/repository/api/v1/tests/test_api_v1.py, django/thunderstore/repository/api/v1/viewsets.py, django/thunderstore/repository/package_upload.py
- Add better error handling for unicode decode failures in manifest.json parsing
- Attempt to improve package rating performance by removing unnecessary querying from the rating view
=> Minor improvements

.devcontainer/celeryCommand.sh, .devcontainer/django.Dockerfile, .devcontainer/docker-compose.yml
=> Add stripped celery cervices to devcontainer

django/conftest.py
=> Add use_static_files_storage fixture

django/thunderstore/repository/templates/repository/package_create.html
This is unlikely to cause an issue but it's a simple fix
=> Fix unsafe innerHTML

Dockerfile
Improve LABEL syntax used in the Django Dockerfile, making PyCharm's
Dockerfile linter happy
=> Improve Dockerfile label syntax

django/thunderstore/account/forms.py, django/thunderstore/core/types.py, django/thunderstore/repository/api/v1/views.py, django/thunderstore/repository/models/uploader_identity.py, django/thunderstore/repository/package_upload.py, django/thunderstore/repository/permissions.py
=> Add UserType

django/thunderstore/community/templates/community/packagelisting_list.html
Add a title to provide alt text for long package display name.
=> Add title to package list item

docker-compose.yml, docker/docker-compose.pytest.yml
Replaces #278 (see https://github.com/thunderstore-io/Thunderstore/pull/278#issuecomment-798868374)
=> Update Postgres to 12.6

builder/src/scss/general.scss, django/thunderstore/community/templates/community/packagelisting_detail.html, django/thunderstore/community/templates/community/packagelisting_list.html, django/thunderstore/repository/models/package.py, django/thunderstore/repository/templates/repository/packageversion_detail.html, django/thunderstore/repository/views/repository.py, django/thunderstore/webhooks/models.py
- Fix cache key collision
- Align category badges better
- Add categories to webhook updates
- Reorganize package version detail page
- Disable invalid annotations
=> Several small fixes

.github/workflows/test.yml
I'm not sure why the previous solution didn't work (the pull request runs on #332 were skipped) but this should be more robust anyway.
=> Fix test workflow check

.github/workflows/test.yml
=> Disable Push and Build for forks

README.md, django/pytest.ini, django/thunderstore/community/middleware.py, django/thunderstore/core/settings.py, django/thunderstore/core/urls.py, django/thunderstore/frontend/templatetags/auth_login.py, django/thunderstore/frontend/tests/test_views.py, docker-compose.yml
- Handle community not found 404 better (don't return a templated response)
- Add support for a dedicated auth domain
=> Auth improvements

django/thunderstore/repository/admin.py
=> Make Packages sortable by file size in djangoadmin

django/conftest.py, django/thunderstore/community/context_processors.py, django/thunderstore/frontend/templatetags/dynamic_html.py, django/thunderstore/frontend/tests/test_errors.py, django/thunderstore/frontend/views.py, django/thunderstore/repository/context_processors.py, django/thunderstore/repository/tests/test_views.py
- Disable caching from 404 pages under the static path
- Return proper status codes on 500 and 404 errors
=> Improve error pages

django/thunderstore/core/tests/test_management_commands.py
=> Add tests for create_test_data management command

django/thunderstore/cache/cache.py, django/thunderstore/cache/tasks.py, django/thunderstore/community/models/package_listing.py, django/thunderstore/core/settings.py, django/thunderstore/core/tests/test_celery.py, django/thunderstore/core/utils.py, django/thunderstore/frontend/models.py, django/thunderstore/repository/admin.py, django/thunderstore/repository/models/package.py, django/thunderstore/repository/models/package_version.py, django/thunderstore/repository/tests/test_package_cache.py, django/thunderstore/repository/tests/test_utils.py, django/thunderstore/repository/tests/test_views.py
Implement several performance improvements, including a fix for the slow package upload handling.
=> Performance improvements

.pre-commit-config.yaml, django/thunderstore/community/tests/test_community.py, django/thunderstore/core/types.py
Ran into a problem whilst working on #544 https://github.com/thunderstore-io/Thunderstore/runs/5840049002?check_suite_focus=true#step:11:45
This should fix it
=> Update black from 20.8b1 to 22.3.0

django/thunderstore/community/models/package_listing.py, django/thunderstore/community/templates/community/packagelisting_detail.html, django/thunderstore/community/templates/community/packagelisting_list.html, django/thunderstore/community/urls.py, django/thunderstore/core/urls.py, django/thunderstore/frontend/templates/base.html, django/thunderstore/frontend/tests/test_views.py, django/thunderstore/repository/models/package.py, django/thunderstore/repository/models/package_version.py, django/thunderstore/repository/templates/repository/package_create.html, django/thunderstore/repository/templates/repository/package_create_old.html, django/thunderstore/repository/templates/repository/packageversion_detail.html, django/thunderstore/repository/tests/test_views.py, django/thunderstore/repository/urls.py, django/thunderstore/repository/views/repository.py
Add new package urls
Move old package urls, under old_urls namespace
Improve views tests for both new and old urls
=> Introduce new package urls

django/thunderstore/frontend/api/experimental/serializers/views.py, django/thunderstore/frontend/api/experimental/tests/test_community_package_list.py, django/thunderstore/frontend/api/experimental/views/community_package_list.py
Pagination is implemented as an infinite scroll, so each response
contains information whether there's more items to fetch.
Refs TS-231
=> Add pagination support to new UI's community's package list view

django/poetry.lock, django/pyproject.toml
=> Update markdown-it-py package

django/thunderstore/frontend/api/experimental/serializers/views.py, django/thunderstore/frontend/api/experimental/views/package_details.py
=> Experimental API: Include community's bg image in package detail view

django/thunderstore/repository/api/v1/tests/test_api_v1.py, django/thunderstore/repository/api/v1/views.py, django/thunderstore/repository/api/v1/viewsets.py, django/thunderstore/repository/cache.py, django/thunderstore/repository/mixins.py, django/thunderstore/repository/models/cache.py, django/thunderstore/repository/tests/test_bot_api.py, django/thunderstore/repository/tests/test_cache_models.py, django/thunderstore/repository/tests/test_query_performance.py, django/thunderstore/repository/urls.py
- Add new API v1 urls
- Fix caching to work with old and new urls
- Improve tests to cover old and new urls
BLOCKED BY #543
=> Add new API v1 urls

django/thunderstore/repository/tests/test_views.py, django/thunderstore/repository/views/repository.py
Add support for downloading any package regardless of the community
through the domain declared in the PRIMARY_HOST setting.
Refs TS-384
=> Support community-agnostic download links

django/poetry.lock, django/pyproject.toml, django/thunderstore/social/providers.py, django/thunderstore/social/tests/test_complete_login.py, django/thunderstore/social/tests/test_providers.py
=> Experimental API: use pydantic to validate OAuth responses

django/thunderstore/social/api/experimental/views/complete_login.py, django/thunderstore/social/tests/test_complete_login.py
=> Experimental API: return username and email upon login

django/thunderstore/core/settings.py
Enable the Celery integration provided by Sentry
Refs TS-466
=> Enable Sentry Celery integration

django/thunderstore/usermedia/s3_upload.py, django/thunderstore/usermedia/tests/test_cleanup.py
Fix cleanup of expired but invalid UserMedia objects. This should solve
a scenario where a multi-part upload doesn't exist when we attempt to
delete it, resulting in a failure.
Refs TS-559
=> Fix invalid UserMedia cleanup

django/thunderstore/repository/admin/__init__.py, django/thunderstore/repository/admin/package_version.py, django/thunderstore/repository/admin/tests/test_package_version.py
Add standalone list and detail views for the PackageVersion in order to
make it easier to manage them in mass quantities.
Refs TS-598
=> Add standalone admin views for PackageVersion

README.md
Remove or update outdated sections from README.md
=> Remove outdated information from README.md

django/thunderstore/core/settings.py
Read S3 mirror configs from env variables and add mirror to storage mirrors if required env variables are configured.
=> Add S3 mirror configs

django/thunderstore/core/settings.py
Fixed the type hint error that prevented the build to succeed.
=> Fix s3 mirror settings

django/thunderstore/frontend/templates/frontend/manifest_v1_validator.html, django/thunderstore/frontend/templates/frontend/markdown_preview.html, django/thunderstore/repository/templates/repository/package_create.html, django/thunderstore/repository/templates/repository/package_create_old.html, django/thunderstore/repository/templates/repository/package_docs.html, django/thunderstore/social/templates/settings/base.html
validator
markdown
create
create_old
docs
setting base
refs TS-1130
=> Disable left, right and content_end from few pages

.gitignore, builder/src/scss/all.scss, builder/src/scss/base.scss, builder/src/scss/general.scss, minio/thunderstore-entrypoint.sh
Set a minimum page height of at least one screen and ensure the footer
is at the bottom of it rather than in the middle for shorter pages.
Refs TS-1332
=> Set a minimum page height

builder/src/api.ts, builder/src/components/FormSelectField.tsx, builder/src/components/PackageManagement/Categories.tsx, builder/src/components/PackageManagement/Panel.tsx, django/thunderstore/community/api/experimental/views.py, django/thunderstore/repository/tests/test_views.py, django/thunderstore/repository/views/repository.py
Implement a proof-of-concept level solution for package category management accessible to package authors.
While not pretty, this solution should suffice as a MVP solution if a fast release is needed.
Refs TS-1334
Video for reference: https://streamable.com/xxdmue
=> Implement PoC category management controls

django/thunderstore/community/api/experimental/serializers.py, django/thunderstore/frontend/tests/test_views.py
Fix the API docs and add a test which ensures we don't break them in the future without realizing
No refs
=> Fix API docs and add a test for them

django/thunderstore/community/admin/package_listing.py, django/thunderstore/repository/admin/package.py
Change a few admin pages to be easier & more performant to browse
=> Slight admin improvements

django/conftest.py, django/thunderstore/community/templates/community/packagelisting_detail.html, django/thunderstore/repository/models/package.py, django/thunderstore/repository/templates/repository/packageversion_detail.html
Add a dedicated panel for displaying changelogs to the package page if the package includes a dedicated changelog file.
Refs TS-1415
Resolves #15
=> Display changelogs on package page if available

django/thunderstore/core/management/commands/create_test_data.py
Include changelog in the packages that are created by the create_test_data script
Refs TS-1417
=> Include changelog in create_test_data script

README.md, django/thunderstore/core/management/commands/create_test_data.py, django/thunderstore/core/tests/test_management_commands.py
Support creation of Community & CommunitySite test data with the
create_test_data command
=> Community & CommunitySite test data creation

django/thunderstore/repository/tests/test_views.py, django/thunderstore/repository/views/repository.py
Make the breadcrumb links on package listing views community-aware
Refs TS-1427
=> Make breadcrumb urls community-aware

django/thunderstore/core/settings.py, django/thunderstore/schema_import/schema.py, django/thunderstore/schema_import/sync.py
The ecosystem schema is going to change so that communities are separated from game definitions entirely. This commit implements support for importing communities in accordance with the new structure.
Refs TS-1477
=> Update schema import to accommodate new structure

django/thunderstore/community/middleware.py, django/thunderstore/community/models/community_site.py, django/thunderstore/core/utils.py, django/thunderstore/repository/api/v1/serializers.py, django/thunderstore/repository/api/v1/tasks.py, django/thunderstore/repository/api/v1/tests/test_api_v1.py, django/thunderstore/repository/api/v1/tests/test_package_index_build.py, django/thunderstore/repository/api/v1/tests/test_serializers.py, django/thunderstore/repository/api/v1/viewsets.py, django/thunderstore/repository/tests/test_query_performance.py
Remove the reliance on community_site context from the API serializers
Refs TS-1502
**Merge #795 first!**
=> Remove reliance on community_site from API

django/thunderstore/community/templates/community/packagelisting_detail.html, django/thunderstore/repository/api/experimental/tests/test_api_experimental_submit.py, django/thunderstore/repository/api/experimental/views/submit.py, django/thunderstore/repository/templates/repository/packageversion_detail.html, django/thunderstore/repository/views/repository.py
Fixes:
- Manual download links
- Post-upload redirect (old uploader)
- Post-upload result URLs (new uploader)
Refs TS-1509
=> Fix some URL building issues that weren't accounted for yet

django/thunderstore/core/management/commands/create_test_data.py, django/thunderstore/core/tests/test_management_commands.py
Add test data creation support for LegalContract and LegalContractVersion
Refs TS-1559
=> Implement test data creation for legal docs

django/thunderstore/frontend/templates/base.html
Add a second navbar dedicated for community-specific content and move some items there.
Refs TS-1510
Sample
=> Add a community-specific subnav

django/overwolf_auth/README.md, django/overwolf_auth/__init__.py, django/overwolf_auth/apps.py, django/overwolf_auth/backends.py, django/overwolf_auth/cached_jwk_client.py, django/overwolf_auth/compat.py
The app adds support for authenticating via Overwolf's OAuth2 service.
This commit doesn't yet include the required changes to settings.py (see the README) nor is the login link available on the UI.
Refs TS-1578
=> Add overwolf_auth app

django/thunderstore/repository/models/package.py, django/thunderstore/repository/models/package_version.py, django/thunderstore/repository/serializer_fields.py, django/thunderstore/repository/tests/test_package_manifest.py, django/thunderstore/repository/tests/test_serializer_fields.py
=> Fix typos in some error messages

django/poetry.lock, django/pyproject.toml, django/thunderstore/__init__.py, django/thunderstore/core/setting_urls.py, django/thunderstore/core/settings.py, django/thunderstore/frontend/views.py, django/thunderstore/plugins/base.py, django/thunderstore/plugins/loading.py, django/thunderstore/plugins/registry.py, django/thunderstore/plugins/types.py, django/thunderstore/repository/views/team_settings.py, django/thunderstore/social/templates/settings/base.html, django/thunderstore/social/views.py, docker-compose.yml
Implement a plugin system MVP, allowing for more modular codebase architecture.
This PR includes a handful of hook points, specifically:
- Django settings
- Django installed apps
- User setting URLs
- User setting page links
More will be added as followup PRs as necessary
=> Plugin system MVP

django/thunderstore/api/cyberstorm/serializers/__init__.py, django/thunderstore/api/cyberstorm/serializers/community.py, django/thunderstore/api/cyberstorm/tests/test_community_detail.py, django/thunderstore/api/cyberstorm/tests/test_community_list.py, django/thunderstore/api/cyberstorm/views/__init__.py, django/thunderstore/api/cyberstorm/views/community_detail.py, django/thunderstore/api/cyberstorm/views/community_list.py, django/thunderstore/api/ordering.py, django/thunderstore/api/urls.py, django/thunderstore/community/models/community.py
Add community detail endpoint
Add community list endpoint
refs TS-1682
=> Add CS community endpoints

django/thunderstore/social/api/experimental/views/current_user.py, django/thunderstore/social/tests/test_current_user.py
=> Add cyberstorm_beta_access flag check to current_user

django/thunderstore/core/settings.py
Make the uid field searchable on social auth admin
=> Admin: Add uid to social auth search fields

builder/src/scss/code-input.scss, django/poetry.lock, django/pyproject.toml, django/thunderstore/plugins/base.py, django/thunderstore/plugins/registry.py, django/thunderstore/repository/urls.py, django/thunderstore/repository/views/mixins.py, docker-compose.yml
This PR will add a new "Source" tab on the package detail page which will contain decompiled source of the package (if available).
=> Add a source tab to the package detail page

django/poetry.lock, django/pyproject.toml
Update the sentry-sdk library and include the celery integration feature for it.
=> Update sentry-sdk and include celery integration

django/thunderstore/social/api/experimental/views/current_user.py, django/thunderstore/social/tests/test_current_user.py
Introduce back the old 'teams' field in the current user experimental API, as it's used by some API clients. Provide the new structure in a 'teams_full' field instead.
Additionally make the OAuth connection rendering not fail if some field is missing, as we can't guarantee any of the extra data to exist.
=> Fix recently introduced issues in experimental API

.github/workflows/deploy.yml
Add a GitHub Actions workflow which can be used to trigger a deployment workflow in another repo.
=> Add a GitHub Actions workflow for deployment

django/thunderstore/api/cyberstorm/views/team.py
Based on non-blocking review comment.
Refs TS-1856
=> Cyberstorm API: simplify team fetching on team-related list views

docker-compose.yml, docker/docker-compose.pytest.yml, docs/db-upgrade.md
Update the development environment postgres version to 13.12 in order to match production.
Also include short docs for how to upgrade the dev env db without losing data if that's needed.
=> Update dev env postgres to 13.12

django/thunderstore/api/cyberstorm/tests/test_package_versions.py, django/thunderstore/api/cyberstorm/views/__init__.py, django/thunderstore/api/cyberstorm/views/package_versions.py, django/thunderstore/api/urls.py
=> Cyberstorm API: add endpoint for Package's versions

django/thunderstore/api/cyberstorm/views/team.py
Add usage of conditional_swagger_auto_schema
Reduce constraints of serializers
=> Refine AddTeamMemberAPIView

django/thunderstore/api/cyberstorm/views/markdown.py, django/thunderstore/api/cyberstorm/views/package_detail.py
=> Use keyword arguments to be explicit

django/thunderstore/api/cyberstorm/tests/test_markdown.py, django/thunderstore/api/cyberstorm/tests/test_package_details.py, django/thunderstore/api/cyberstorm/views/markdown.py, django/thunderstore/api/cyberstorm/views/package_detail.py
=> Cyberstorm API: annotate has_changelog on PackageDetailAPIView

.github/workflows/test.yml, django/thunderstore/community/models/community.py, django/thunderstore/community/models/package_listing.py, django/thunderstore/community/tests/test_community.py, django/thunderstore/permissions/tests/test_validate_user.py, django/thunderstore/permissions/utils.py, django/thunderstore/repository/models/package.py, django/thunderstore/repository/models/team.py, django/thunderstore/repository/permissions.py, django/thunderstore/repository/tests/test_package.py, django/thunderstore/repository/tests/test_team.py
Replace multiple instances of copypaste code with a common implementation.
In some instances the replacement is slightly different than previously, but this is intended as some of the replaced checks were more lax than intended.
=> Reduce permissions boilerplate

django/thunderstore/frontend/templates/base.html
Update the hardcoded footer content, specifically the year number and discord invite link.
=> Update hardcoded footer content

builder/src/scss/general.scss, django/thunderstore/frontend/templates/base.html
Read commit messages for the specifics
=> Minor layout fixes

django/thunderstore/repository/migrations/0048_populate_visibility.py
Add a data migration which populates the visibility field of PackageVersion objects
=> Popuplate PackageVersion visibility field

django/thunderstore/community/admin/package_listing.py
Custom filter was used rather than the ordering meta field of the Community class since the latter might have some uninteded consequences elsewhere.
=> Sort community filter options alphabetically on package listing admin

.github/workflows/test.yml
Update artifact@v3 to artifact@v4 to fix Build & Test workflow check
=> Update artifact@v3 to artifact@v4

django/thunderstore/api/cyberstorm/serializers/package.py, django/thunderstore/api/cyberstorm/tests/test_package_listing_list.py, django/thunderstore/api/cyberstorm/views/package_listing_list.py
=> Add datetime_created to packagelisting api (TS-2343)

django/thunderstore/repository/api/v1/views/listing_index.py
This is a speculative change attempting to bring the performance of chunked package list API endpoint on par with the older unchunked API endpoint.
The older enpoint also uses django.utils.cache.get_conditional_response but it was decided to omit this on chunked endpoint as none of the HTTP headers required for it to work are sent by TSMM.
Refs TS-2376
=> Add Last-Modified header to chunked package list API response

docs/rfc_service_layer_document.md, docs/service_layer_implementation_guide.md
* Add implementation guide
* Add full proposal doc
=> Implement docs for service layer pattern refactor (TS-2412)

django/thunderstore/social/templates/settings/delete_account.html, django/thunderstore/social/views.py
Show teams on Delete Account page
Get rid of autocomplete on verification input
Adjust wording of warning
=> Show teams on Delete Account page

django/thunderstore/api/cyberstorm/serializers/community.py, django/thunderstore/api/cyberstorm/tests/test_community.py
Add has_mod_manager_support to Cyberstorm Community API
=> Add has_mod_manager_support to Cyberstorm Community API (TS-2401)

django/thunderstore/repository/package_manifest.py, django/thunderstore/repository/tests/test_utils.py, django/thunderstore/repository/utils.py, django/thunderstore/social/utils.py
Move package_exists_in_any_case from social.utils to repository.utils
=> Move package_exists_in_any_case to correct utils (TS-2446)

django/thunderstore/api/cyberstorm/tests/test_package_listing_list.py, django/thunderstore/api/cyberstorm/views/package_listing_list.py
Use subqueries to avoid overcounting downloads and ratings in PackageListing annotations.
Refs. TS-2551
=> Fix incorrect download count in cyberstorm api(TS-2551)

django/thunderstore/api/cyberstorm/services/package_listing.py, django/thunderstore/api/cyberstorm/tests/endpoint_data.py, django/thunderstore/api/cyberstorm/tests/services/test_package_listing_services.py, django/thunderstore/api/cyberstorm/tests/test_package_listing_actions.py, django/thunderstore/api/cyberstorm/tests/utils.py, django/thunderstore/api/cyberstorm/views/__init__.py, django/thunderstore/api/cyberstorm/views/package_listing_actions.py, django/thunderstore/api/urls.py
- Implement view for unlisting packages
- Implement service for unlisting packages
- Add URL path
- Implement tests
=> Cyberstorm api unlist package (TS-2597)

django/thunderstore/api/cyberstorm/serializers/__init__.py, django/thunderstore/api/cyberstorm/serializers/team.py, django/thunderstore/api/cyberstorm/services/team.py, django/thunderstore/api/cyberstorm/tests/endpoint_data.py, django/thunderstore/api/cyberstorm/tests/services/test_team_services.py, django/thunderstore/api/cyberstorm/tests/test_endpoints.py, django/thunderstore/api/cyberstorm/tests/test_update_team_member.py, django/thunderstore/api/cyberstorm/tests/utils.py, django/thunderstore/api/cyberstorm/views/__init__.py, django/thunderstore/api/cyberstorm/views/team.py, django/thunderstore/api/urls.py, django/thunderstore/repository/forms/team.py, django/thunderstore/repository/tests/test_team_forms.py, django/thunderstore/repository/views/team_settings.py
* Implement endpoint for updating team members
* Support only role at this point
* Implement tests
* Implement service layer function for updating team members & implement tests
* Use service layer function in form view responsible for demote&promote team members
* Update form tests
=> Implement update team member endpoint (TS-2316)
