- django/repository/templatetags/markdownify.py
The template will escape everything hitting it anyway.
Tested with https://thunderstore.io/package/ToyDragon/SharedModLibrary/ and its now all the quotation marks are actually `"` and not `&quot;`
> Remove escaping pre template

- builder/src/scss/general.scss
I feel as though the deep blue of the rated mods looked out of place on the site. I've changed the icon color to be a lighter blue (#3498db, the current color of the alert banner near the top of the page) to better match the color scheme.
> Update color of the 'rated' icon

- django/repository/templates/repository/package_detail.html
Adds the 'fa-globe' icon to the website link on package detail pages.
Original: https://funkfrog.me/cjAXDDwRiZ.png
Modified: https://funkfrog.me/ZIaAG70DIb.png
Resolves issue #19
> Add the 'fa-globe' icon to the website link

- django/frontend/templates/base.html
Adds a link to the API docs in the navbar. 
Before: https://funkfrog.me/kOQluONGTD.png
After:
https://funkfrog.me/QlojN6yZ6H.png Regular Monitor Width
https://funkfrog.me/9FhriVUqGG.png iPhone X
https://funkfrog.me/1rGxj8joOI.png iPad
https://funkfrog.me/L7z8BetsRI.png Galaxy S9
Resolves #21
> Add link to the API documentation

- .github/workflows/release.yml
Minor change so that pushing the images in the release workflow are in separate steps to mirror the test workflow
This also makes the workflow slightly more resilient in case logging in to GHCR fails
> Separate push steps in release

- .github/workflows/test.yml
I don't think it is possible to only run it if tests is the one that fails (so it might try to upload coverage even if the first step failed) but this shouldn't really be an issue as the job failed anyway
> Upload code coverage even if tests fail

- .github/workflows/test.yml
- django/pytest.ini
In general this is not required, especially with codecov now in use for every pushed commit. External tools (e.g. IDE integrations) don't need this data which adds extra time for something that probably makes more sense to be opt-in anyway as when it is used, it is used with `docker-compose exec`, meaning any needed coverage options can be added easily
> Remove default pytest cov args

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/postAttach.sh
- .gitignore
- .vscode/launch.json
- django/.gitignore
- docker-compose.yml
- docker/builder.Dockerfile
> Add devcontainer

- docker-compose.yml
This makes all Django services other than `django` use read-only bind mounts to avoid permission issues when using the devcontainer. New services should follow this to avoid having to make a second devcontainer-specific image which uses a non-root main user.
> Change django service volumes to read-only

- django/pytest.ini
- django/thunderstore/core/settings.py
- docker-compose.yml
- docker/builder.Dockerfile
- pgbouncer.ini
Add support for transaction-level database connection pooling via PgBouncer. To ensure consistency with the production environment, also include PgBouncer in the development environment and configure Django tests to run through it.
To-do:
> Add support for PgBouncer transaction-level connection pooling

- .github/workflows/test.yml
This will stop:
- Waiting for 2 workflows to complete that are doing the same thing
- Having codecov updated twice for the same commit
- Having two Docker images pushed to the same tag (based on commit SHA) which might not be the same
- Commit images are expected to be static
> Stop running pull request workflow on internal PRs

- django/thunderstore/repository/api/v1/serializers.py
Ensure download URLs are generated to point to HTTPS when the site has
been configured to use HTTPS in the settings
No refs
> Add better scheme handling in API v1

- django/thunderstore/core/settings.py
Adds a setting for easy-thumbnails to preserve png extension. Since icons are required to be uploaded as pngs, this guarantees in practice that all thumbnails will be pngs. Currently thumbnails are shown as 85% quality JPEGs, which can [make some thumbnails ugly](https://cdn.thunderstore.io/live/repository/icons/olavim-RoundsWithFriends-1.2.4.png.256x256_q85_crop.jpg).
Tested by
1. Run the project once without any changes, setup stuff in djangoadmin, and upload a test package with a known bad quality thumbnail.
2. Add the setting change.
3. Restart the project. The setting did not apply immediately, and the thumbnail was still porrige when I refresh thunderstore in browser.
4. Run `docker-compose exec django python manage.py clear_cache` in a terminal (having this command documented would …
> Preserve thumbnail png extension

- builder/package.json
- builder/src/api.ts
- builder/src/components/CodeInputPanel.tsx
- builder/src/components/FormSelectField.tsx
- builder/src/components/ProgressBar.tsx
- builder/src/debounce.ts
- builder/src/main.ts
- builder/src/manifest.tsx
- builder/src/markdown.tsx
- builder/src/scss/all.scss
- builder/src/scss/code-input.scss
- builder/src/scss/markdown.scss
- builder/src/upload.tsx
- builder/yarn.lock
- django/thunderstore/core/urls.py
- django/thunderstore/frontend/templates/base.html
- django/thunderstore/frontend/templates/frontend/manifest_v1_validator.html
- django/thunderstore/frontend/templates/frontend/markdown_preview.html
- django/thunderstore/frontend/tests/test_views.py
- django/thunderstore/frontend/views.py
- django/thunderstore/repository/package_manifest.py
- django/thunderstore/repository/serializer_fields.py
- django/thunderstore/repository/templates/repository/package_create.html
- django/thunderstore/repository/tests/test_package_manifest.py
- django/thunderstore/repository/tests/test_serializer_fields.py
- django/thunderstore/repository/validation/tests/test_manifest.py
Add some useful tools for authors to make submission of large packages less painful, specifically:
- Add a tool which can be used to preview markdown
- Add a tool which can be used to validate a manifest before upload
Also make minor improvements to the package submission page overall.
> Add markdown preview & manifest validator tools

- django/thunderstore/core/management/commands/create_test_data.py
- django/thunderstore/repository/admin.py
- django/thunderstore/repository/api/v1/serializers.py
- django/thunderstore/repository/views/repository.py
- Add file size display to django admins package object listing
- Add file size keyvalue to api/v1/package response json
- Fix create_test_data management command
- Fix package searches ending with a space, to not return all packages
> Multiple small fixes to Thunderstore

- django/thunderstore/repository/admin.py
Fix an issue where the package admin page would crash if the latest was
set to None for whatever reason on any package.
> Fix an issue with admin page crashing

- loadtest/locustfile.py
While this still only makes requests to the front page, the query
parameters cause different database queries to be executed.
> Use random query parameters when load testing with locust

- .flake8
- django/thunderstore/core/settings.py
Make it possible to enable debug toolbar for superusers only, allowing
it to be safely run in production to debug performance.
> Allow enabling debug toolbar for superusers only

- Dockerfile
- django/poetry.lock
- django/pyproject.toml
- django/thunderstore/abyss/middleware.py
- django/thunderstore/abyss/storage.py
- django/thunderstore/core/settings.py
Add a middleware that uses abyss to generate and store traces to the
configured storage.
Only generate traces for requests by superusers with a specific
parameter set.
> Add abyss middleware

- django/thunderstore/cache/tasks.py
- django/thunderstore/core/utils.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_utils.py
- django/thunderstore/utils/decorators.py
- django/thunderstore/utils/tests/test_decorators.py
Fix webhooks used for release announcements, which had a bug caused by
not properly accounting for python's variable scoping/capture logic.
The on_commit hook ended up referring to the same object for each
webhook call, which meant only one of the webhooks ever triggered if
package had multiple webhooks defined, and that webhook would trigger
multiple times.
> Fix release webhooks

- django/thunderstore/markdown/templatetags/markdownify.py
Markdown-it-py throws an IndexError with the following content:
> QUOTE\n
+ UNORDERED LIST ITEM\n
> INDENTED QUOTE\n
\n\n
Removing any of the three content rows or reducing the number of
newlines at the end seems to solve the issue. While stripping the
markdown before rendering might not be the most robust solution, it'll
be enough to fix an issue currently encountered in production.
Refs TS-228
> Fix edge case in markdown rendering

- django/thunderstore/cache/cache.py
- django/thunderstore/core/settings.py
- django/thunderstore/repository/api/v1/serializers.py
- django/thunderstore/repository/api/v1/tasks.py
- django/thunderstore/repository/api/v1/tests/test_api_v1.py
- django/thunderstore/repository/api/v1/viewsets.py
- django/thunderstore/repository/cache.py
- django/thunderstore/repository/tests/test_query_performance.py
Swap from redis to s3 for the v1 API package list. This is a good idea
as the cache was getting large enough for some communities to cause load
issues.
> Swap to s3 backed v1 API package list cache

- django/thunderstore/cache/cache.py
- django/thunderstore/cache/pagination.py
Implement the change made in commit
5a87fb33022e1f08dac9c07a12e74f75069333bb in a less complex way by
moving the cache timeout to the caching function as a default, instead
of explicitly setting it on all of the call sites as that is not the
intention.
> Reduce cache code complexity slightly

- django/thunderstore/repository/forms/team.py
- django/thunderstore/repository/models/team.py
- django/thunderstore/repository/templates/settings/team_base.html
- django/thunderstore/repository/templates/settings/team_donation_link.html
- django/thunderstore/repository/tests/test_team.py
- django/thunderstore/repository/tests/test_team_forms.py
- django/thunderstore/repository/tests/test_views.py
- django/thunderstore/repository/urls.py
- django/thunderstore/repository/views/team_settings.py
Add a new settings page which allows for the donation link field on a
team to be filled by the team's owner.
Visual preview (screenshot text is outdated, but otherwise matches):
**BLOCKED BY #539**
> Add team donation link settings page

- django/thunderstore/repository/api/v1/serializers.py
- django/thunderstore/repository/api/v1/tests/test_api_v1.py
Expose the recently added team donation link field over the v1 API. Omit
the key entirely for packages which have no donation link set as to
ensure backwards compatibility in case the field is removed in the
future.
**BLOCKED BY #539**
> Expose team donation links over v1 API

- django/thunderstore/community/middleware.py
- django/thunderstore/community/tests/test_middleware.py
- django/thunderstore/social/templates/settings/linked_accounts.html
This pull requests introduces a fix to a bug that is preventing OAuth accounts from being linked to the logged in user in some subdomains due to invalid redirect URLs.
Additionally some improved default behavior for the auth domain is included, which should lead to less dead ends if the OAuth process fails for some reason.
> Fix OAuth account linking

- django/thunderstore/repository/mixins.py
- django/thunderstore/repository/tests/test_views.py
We need to raise Http404 if the community_identifier does not exist on
any community
refs TS-376
> Fix CommunityMixin def community

- django/thunderstore/repository/models/cache.py
- django/thunderstore/repository/tests/test_cache_models.py
Fix API cache cleanup for cases where there is no API cache to clean up
(due to there being no CommunitySite object assigned and thus no cache
being generated).
Refs TS-379
> Fix API cache cleanup for siteless communities

- django/thunderstore/repository/models/package.py
- django/thunderstore/repository/tests/test_package.py
Use the `PRIMARY_HOST` setting as a fallback when building a package's
full URL if a Site isn't provided.
This is a required change as in the new URL scheme we no longer have a community site context available. However, this can't be relied on before #405 is finalized.
This PR also does not mean we should default to the `PRIMARY_HOST` in every scenario. If possible, we should direct to the community-specific URLs defined in the new URL schema, and this can be done at least for the v1 API just fine.
Refs TS-383
> Use primary host fallback for URL building

- django/thunderstore/repository/api/v1/serializers.py
- django/thunderstore/repository/api/v1/tests/test_api_v1.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package_version.py
Always use the PRIMARY_HOST when building package download URLs for the
API v1, effectively removing the need for a community_site being
available.
Refs TS-385
> Use primary host for API v1 download URLs

- django/thunderstore/core/utils.py
- django/thunderstore/repository/api/v1/tasks.py
- django/thunderstore/repository/api/v1/tests/test_api_v1.py
- django/thunderstore/repository/api/v1/tests/test_caches.py
- django/thunderstore/repository/api/v1/viewsets.py
- django/thunderstore/repository/mixins.py
Enable generation of API v1 cache for communities without a
CommunitySite at all, but make sure to provide at least the community in
the serializer context.
Refs TS-381
> Build API v1 cache for subdomainless communities

- django/thunderstore/social/api/experimental/views/complete_login.py
- django/thunderstore/social/permissions.py
- django/thunderstore/social/tests/test_complete_login.py
When completing the OAuth authentication flow, Next.js backend sends a
request to Django backend. To prevent unwanted access to this endpoint,
a shared secret is sent along the request. This was initially included
in the request body and validated in the view. Now the it's included in
the request headers and validated by a custom DRF permission class.
To make the approach reusable, a base class for easily creating
permission classes based on different secrets is provided.
Refs TS-230, TS-354
> Experimental API: add a permission class based on a shared secret

- django/thunderstore/social/providers.py
- django/thunderstore/social/tests/test_providers.py
It was assumed the local username created by Discord OAuth-based login
would include the discriminator number, e.g. "Foo#1234". But when you
assume things, you make an ass out of u and me.
Refs TS-230, TS-354
This PR replaces #584
> Experimental API: remove discriminator from Discord username

- django/thunderstore/social/api/experimental/views/complete_login.py
- django/thunderstore/social/providers.py
- django/thunderstore/social/tests/test_complete_login.py
- django/thunderstore/social/tests/test_providers.py
Implemented in earlier commits (in UI repo):
1. User clicks an authentication link
2. User's browser stores a "state token" to local storage (for CSRF
prevention) and redirects to OAuth provider's endpoint for login
3. After login, browser is redirected to client-side page, with query
parameters containing the state token (which is validated) and a
"code token"
4. Client-side page sends a request to Next.js API endpoint, which
creates another request containing the code token and a "shared
secret token" (for brute force prevention). For security reasons
the latter token is not available client-side, which is why this
sidestep is required
5. Next.js API endpoint sends the request to Django API endpoint
6. Django API endpoint validates the shared secret token
7. The endpoint sends a request …
> Experimental API: create user account based on OAuth login

- django/thunderstore/social/api/experimental/views/complete_login.py
- django/thunderstore/social/tests/test_complete_login.py
Implemented in earlier commits (in UI repo):
1. User clicks an authentication link
2. User's browser stores a "state token" to local storage (for CSRF
prevention) and redirects to OAuth provider's endpoint for login
3. After login, browser is redirected to client-side page, with query
parameters containing the state token (which is validated) and a
"code token"
4. Client-side page sends a request to Next.js API endpoint, which
creates another request containing the code token and a "shared
secret token" (for brute force prevention). For security reasons
the latter token is not available client-side, which is why this
sidestep is required
5. Next.js API endpoint sends the request to Django API endpoint
6. Django API endpoint validates the shared secret token
7. The endpoint sends a request …
> Experimental API: WIP implementation for authentication, pt4

- django/thunderstore/frontend/api/experimental/tests/test_package_details.py
- django/thunderstore/frontend/api/experimental/views/package_details.py
> Use 404 instead of 403 to avoid leaking information

- django/thunderstore/social/api/experimental/urls.py
- django/thunderstore/social/api/experimental/views/__init__.py
- django/thunderstore/social/api/experimental/views/validate_session.py
- django/thunderstore/social/tests/test_validate_session.py
Simple endpoint for checking if the user is authenticated, i.e. if the
session key sent in the authorization header is related to active
session stored in the database.
The new UI will use this to check that the session key stored in the
localStorage is still current.
Refs TS-230, TS-358
> Experimental API: add endpoint for checking session validity

- django/thunderstore/frontend/views.py
- django/thunderstore/repository/views/repository.py
Django includes the CSRF token cookie only on pages where the csrf_token
templatetag is used.
As we use it on the API, this means all views which can make API calls
need a CSRF token cookie to be present.
Address the issue by including the CSRF token on all pages which make
API calls.
Refs TS-557
> Ensure CSRF token is present where needed

- django/pytest.ini
- django/thunderstore/community/middleware.py
- django/thunderstore/community/tests/test_middleware.py
- django/thunderstore/frontend/tests/test_views.py
Fix the test for CommunitySiteMiddleware redirects as well as an
edge-case redirect loop that could occur if the PRIMARY_HOST setting is
set to the same value as AUTH_EXCLUSIVE_HOST
> Fix CommunitySiteMiddleware redirects

- django/thunderstore/core/tasks.py
- django/thunderstore/core/tests/test_celery.py
Fixes an issue where the celery_post task was attempting to return
a HTTP response object, which is not possible to serialize into JSON.
It's not easy to write a test which fails for this behavior, as when
the task is eagerly executed (such as during tests) the serialization
step is skipped.
Refs TS-558
> Fix celery_post celery task

- django/thunderstore/usermedia/s3_upload.py
- django/thunderstore/usermedia/tests/test_cleanup.py
Fix error with abort_multipart_upload when UserMedia.upload_id is None
From now on we go with the default of None in upload_id means that the
upload doesn't exist
refs TS-589
> Fix UserMedia abort_multipart_upload bug

- django/thunderstore/frontend/templates/base.html
From discord:
> Wildbook
> [..] right now it's in the order the communities were added. This is pretty suboptimal, and the entire list is way too long by now anyway so it should ideally be completely replaced imo.
> 
> cyber
>  the first suggestion (alphabetical communities dropdown) sounds like a pretty simple pr :ravythink:
> 
> Wildbook 
> Yeah, the issue is mainly with people not having time and the people who do have time wanting to work on the UI rework rather than fixing up the current version of the site 😅
If you want to go make a PR for it I'm pretty sure no one would mind
> sort communities in community dropdown

- builder/src/api.ts
- builder/src/state/FileUpload.ts
- builder/src/upload.tsx
Improve upload page error handling by ensuring some more obscure errors
that weren't previously shown anywhere on the UI get displayed along the
rest of the errors.
Additionally include a special case for handling ETag missing errors
which are usually caused by a browser extension such as ClearURLs
stripping the headers.
Refs TS-560
> Improve upload page error handling

- builder/src/scss/all.scss
- builder/src/scss/navbar.scss
- django/thunderstore/community/context_processors.py
- django/thunderstore/frontend/templates/base.html
Use a two-column layout for the navbar community selection menu and
include some categorization to make finding the most used communities
easier.
Example screenshot:
> Improve navbar community select

- django/thunderstore/core/settings.py
- django/thunderstore/core/storage.py
- django/thunderstore/core/tests/test_storage.py
- django/thunderstore/utils/contexts.py
- django/thunderstore/utils/tests/test_contexts.py
- minio/thunderstore-entrypoint.sh
Revisited version after #626. Changes:
* Moved `TemporarySpooledCopy` to a separate file and added two simple test cases
* `MirroredS3Storage` now uses the higher-level methods instead of poking the internals, which makes for much simpler code 👍🏻 
`MirroredS3Storage` currently has no unit tests of its own - should it?
> Add MirroredS3Storage

- .pre-commit-config.yaml
As the GitLab hosted flake8 repository is no longer public, change the pre-commit hook to use the GitHub repository instead.
> Fix flake8 pre-commit hook

- django/thunderstore/community/api/experimental/serializers.py
- django/thunderstore/community/api/experimental/tests/test_api_package_listing.py
- django/thunderstore/community/api/experimental/urls.py
- django/thunderstore/community/api/experimental/views.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/repository/api/experimental/serializers/main.py
Implement a PackageListing update API endpoint which can be used to
update the categories set to the PackageListing.
Refs TS-1338
> Add a PackageListing update API endpoint

- builder/src/components/PackageManagement/CsrfInput.tsx
- builder/src/components/PackageManagement/Deprecation.tsx
- builder/src/components/PackageManagement/Panel.tsx
- builder/src/main.ts
- django/poetry.lock
- django/pyproject.toml
- django/thunderstore/community/templates/community/packagelisting_detail.html
- django/thunderstore/frontend/extract_props.py
- django/thunderstore/frontend/templatetags/encode_props.py
- django/thunderstore/frontend/tests/data/scripts.html
- django/thunderstore/frontend/tests/test_encode_props.py
- django/thunderstore/frontend/tests/test_extract_props.py
- django/thunderstore/repository/tests/test_views.py
- django/thunderstore/repository/views/repository.py
**Note to reviewer:** a large bulk of the changes here are either generated files or tests, don't be fazed by the LoC on diffs
Replace the package management panel with a version that's implemented in React as opposed to using Django templates.
Additionally include an easy way to pass data between Django and React
Refs TS-1352
> Implement package management panel in React

- builder/src/scss/navbar.scss
Expand the community dropdown from 2 columns to 3 columns. It would be ideally sorted alphabetically per-column, but that's a more complex change in comparison to this one and can be done separately.
Example:
> Use a 3-column layout on community dropdown

- builder/src/scss/navbar.scss
- django/thunderstore/frontend/templates/base.html
Change the community select dropdown to use a column-first ordering, which should be a bit easier to read through.
Refs TS-1373
Example:
> Order community select column-first

- django/thunderstore/community/templates/community/packagelisting_list.html
- django/thunderstore/frontend/templatetags/qurl.py
- django/thunderstore/frontend/tests/test_qurl.py
- django/thunderstore/repository/templates/repository/includes/pagination.html
- django/thunderstore/repository/views/repository.py
Update the qurl template filter to strip unknown query parameters when building new URLs.
Also fix a bug where the search form would reset the section input entirely.
Refs TS-72
> Strip unnecessary query parameters with qurl

- django/thunderstore/community/admin/package_listing.py
- django/thunderstore/community/consts.py
- django/thunderstore/community/models/community.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_admin_package_listing.py
- django/thunderstore/community/tests/test_community.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/frontend/api/experimental/tests/test_community_package_list.py
- django/thunderstore/frontend/api/experimental/tests/test_package_details.py
- django/thunderstore/frontend/api/experimental/views/community_package_list.py
- django/thunderstore/repository/cache.py
- django/thunderstore/repository/tests/test_views.py
- django/thunderstore/repository/views/repository.py
- django/thunderstore/webhooks/models.py
- django/thunderstore/webhooks/tests/test_webhook.py
Exclude rejected package listings from posting webhook updates to the communites they've been rejected from.
Refs TS-1358
> Filter out rejected package listings from webhooks

- django/thunderstore/community/templates/community/packagelisting_list.html
A recent bug fix to the search introduced another bug which made search break for communities that don't have sections defined. Fix it.
Refs TS-1391
> Fix search on communities without sections defined

- django/thunderstore/frontend/api/experimental/tests/test_markdown.py
- django/thunderstore/repository/validation/readme.py
Increase the maximum valid readme size from around 32kb to 100kb
Refs TS-1398
> Bump max readme size to 100kb

- builder/src/api.ts
- builder/src/components/CommunitySelector.tsx
- builder/src/components/FormRow.tsx
- builder/src/components/FormSelectField.tsx
- builder/src/scss/forms.scss
- builder/src/upload.tsx
- django/thunderstore/community/factories.py
- django/thunderstore/repository/api/experimental/serializers/main.py
- django/thunderstore/repository/api/experimental/tests/test_api_experimental_submit.py
- django/thunderstore/repository/api/experimental/views/submit.py
- django/thunderstore/repository/package_upload.py
- django/thunderstore/repository/validation/categories.py
- django/thunderstore/repository/validation/tests/test_categories.py
Allow selection of categories for all communities a package will be
submitted to instead of just the currently active community.
> Add multi-community category select support to the upload page

- django/thunderstore/repository/api/experimental/serializers/__init__.py
- django/thunderstore/repository/api/experimental/serializers/markdown.py
- django/thunderstore/repository/api/experimental/tests/test_api_package_changelog.py
- django/thunderstore/repository/api/experimental/urls.py
- django/thunderstore/repository/api/experimental/views/__init__.py
- django/thunderstore/repository/api/experimental/views/package_version.py
Add an experimental API endpoint which can be used to fetch a package version's changelog, if any exists.
Refs TS-1414
Resolves #430
> Add an API endpoint for package changelogs

- django/thunderstore/community/models/community.py
- django/thunderstore/community/templates/community/packagelisting_detail.html
- django/thunderstore/community/templates/community/packagelisting_list.html
- django/thunderstore/community/tests/test_community.py
- django/thunderstore/frontend/templates/base.html
- django/thunderstore/frontend/templatetags/community_url.py
- django/thunderstore/frontend/templatetags/tests/test_community_url.py
- django/thunderstore/frontend/tests/test_url_reverse.py
- django/thunderstore/frontend/url_reverse.py
- django/thunderstore/repository/templates/repository/package_create.html
- django/thunderstore/repository/templates/repository/package_create_old.html
- django/thunderstore/repository/templates/repository/packageversion_detail.html
Implement a template tag that will generate appropriate community-specific URLs depending on whether the community has a CommunitySite associated with it or not.
Refs TS-1424
> Implement community URL usage in templates

- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/templates/community/packagelisting_list.html
- django/thunderstore/community/tests/test_package_listing.py
Make the URL helper methods of PackageListing objects community-aware and use the new URL schema if the community they belong to has them enabled.
Refs TS-1426
> Make PackageListing URLs community-aware

- builder/src/api.ts
- builder/src/state/FileUpload.ts
A user reported having their entire upload page break when attempting to upload a package, and the culprit for the breakage seems to be an undefined value ending in the list of errors when it should only contain strings.
The root cause was the user's network configuration eating the API response entirely, which somehow resulted in the above scenario and broke the page.
This commit is a speculative fix which should hopefully prevent similar breakage in the future
Refs TS-1479
> Speculative fix to upload page error handling bug

- django/conftest.py
- django/thunderstore/webhooks/models.py
- django/thunderstore/webhooks/tests/test_webhook.py
Fix a bug which caused package listings which were rejected in their own community to broadcast updates to all webhooks rather than not posting anywhere.
Refs TS-1479
> Fix webhooks posting to wrong community

- django/thunderstore/community/context_processors.py
- django/thunderstore/frontend/templates/base.html
- django/thunderstore/repository/mixins.py
- django/thunderstore/repository/templates/repository/package_create_old.html
Have the CommunityMixin overwrite the full community context rather than only parts of it. Also remove some reliance on request variables in places where context variables can be relied on instead.
Refs TS-1496
> Overwrite full community context in CommunityMixin

- django/thunderstore/frontend/templates/base.html
- django/thunderstore/frontend/tests/data/scripts.html
Update the website footer year number to 2023. Not making it automatic given that the current frontend should be gone before 2024.
Refs TS-1421
> Update website footer

- builder/src/upload.tsx
- django/thunderstore/repository/templates/repository/package_create.html
- django/thunderstore/repository/templates/repository/package_create_old.html
- django/thunderstore/repository/views/repository.py
Improve the way the upload pages handle community context and make them less tightly bound to the domain based community selection, or any specific communities at all.
This is not a final iteration of these changes, but it should suffice to make them usable in production.
Refs TS-1497
> Improve community context handling for upload page

- django/thunderstore/frontend/models.py
- django/thunderstore/frontend/templatetags/dynamic_html.py
Update the dynamic HTML template tag to read community from the template context first and only fall back to the request if not found from context.
Also remove the requirement for having a community available in the
context, as some placements can be global.
Refs TS-1511
> Update dynamic HTML to use community context

- .pre-commit-config.yaml
- django/thunderstore/repository/package_manifest.py
- django/thunderstore/repository/tests/test_package_manifest.py
Increase the maximum amount of dependencies for a package to 1000. The number is arbitrary as before, but the 250 limit was crossed with a real use case.
No refs
> Increase max dependency count to 1000

- django/thunderstore/social/api/experimental/views/current_user.py
- django/thunderstore/social/tests/test_current_user.py
If user has an active subscription, mod manager needs to know when it expires. We can't actually get this information until the PayPal related functionality is completed. Meanwhile, use a stub method.
Refs TS-1666
> Extend subscription information returned by API endpoints

- django/thunderstore/frontend/views.py
- django/thunderstore/repository/tests/test_views.py
Add automated tests for the team creation view and fix a bug that was recently introduced on it. The bug was caused due to mixin inheritance working differently from what was expected.
> Fix the team creation view

- django/thunderstore/repository/views/repository.py
Add upload date as the last sorting criteria for "Most Downloaded" and "Top Rated" sorting options. This fixes an issue where packages with equal amounts of ratings or downloads would get arbitrarily sorted in search results, sometimes leading to a subset of the results never being visible on any page (if a sufficiently large group of same-priority sorting packages exists).
Thanks for keks307 on the Inscryption Modding discord for noticing this.
No refs
> Improve package list sorting priority

- django/thunderstore/api/cyberstorm/serializers/community.py
- django/thunderstore/api/cyberstorm/views/community_list.py
- django/thunderstore/community/models/community.py
- django/thunderstore/community/tests/test_community.py
Moving from placeholder implementation to the real deal on the client side has revealed some shortcomings in the functionality and the returned data of this endpoint.
- Add support for varying page size via page_size query param
- Add support for filtering based on name and description fields via search query param
- Add support for ordering by name and datetime_created fields
- Add datetime_created and icon_url to serializer
- Fields that can return null due to having Null=True in model definition are marked as optional in the serializer
- Add naive implementations for Community's total_package_count and total_downloads_count properties
- Add less naive implementation for icon_url property
Refs TS-1815
> Make community_list endpoint support required functionality

- django/thunderstore/repository/filetree.py
- django/thunderstore/repository/package_upload.py
- django/thunderstore/repository/tasks/files.py
- django/thunderstore/repository/tests/test_package_upload.py
Automatically extract the file tree of new package uploads as they're processed.
This can lead to a potential issue with submission processing time taking much longer than before, and as it's handled synchronously, it could lead to an increase in submission failures for large packages.
There's no way to fix the above issue without moving to an entirely asynchronous submission processing, which is a task too large to take on currently.
> Add automatic file tree extraction on upload

- django/thunderstore/webhooks/admin.py
- django/thunderstore/webhooks/forms/__init__.py
- django/thunderstore/webhooks/forms/webhook.py
- django/thunderstore/webhooks/tests/test_forms_webhook.py
Improve the webhook creation process performance by only allowing category selection after the webhook has been saved once, which allows for them to be filtered based on the community selected for the webhook.
> Admin: Improve Webhook creation performance

- django/thunderstore/community/admin/package_listing.py
- django/thunderstore/community/forms/package_listing.py
- django/thunderstore/community/tests/test_forms_package_listing.py
The PackageListing creation admin form was getting slowed down due to listing every category in the form before a community was selected.
Fix this by disallowing selection of categories before the object is saved once and a community is set, as setting a community will narrow down the applicable categories to a manageable level.
> Admin: Improve PackageListing creation performance

- django/thunderstore/community/admin/package_listing.py
A dropdown at >100 communities is no longer practical, so swap it to a raw ID field which has a proper selection dialog.
> Admin: Add 'community' to PackageListAdmin raw_id_fields

- django/thunderstore/repository/admin/package.py
- django/thunderstore/repository/admin/tests/test_package.py
- django/thunderstore/repository/models/package.py
Improve the chances of the get_absolute_url function for the Package model to return an actual valid & functional URL. The function is only used on Django admin currently, and will generate broken links if the pacckage exists in a different community than the one bound to the active domain.
This change makes it so the first active package listing's page URL is returned instead.
> Admin: Improve get_absolute_url of the Package model

- builder/src/components/PackageManagement/Panel.tsx
- django/thunderstore/community/templates/community/packagelisting_detail.html
- django/thunderstore/repository/tests/test_views.py
- django/thunderstore/repository/views/repository.py
Add links to the relevant admin pages on the package detail page if the current user has permissions to view them.
Preview:
> Admin: Add shortcuts to package admin views

- django/thunderstore/account/admin/__init__.py
- django/thunderstore/account/admin/tests/test_user_admin.py
- django/thunderstore/account/admin/user.py
- django/thunderstore/account/migrations/0004_add_usersettings.py
- django/thunderstore/account/models/user_settings.py
Override the default user admin pages and include Thunderstore-specific extra information on them.
Specifically:
- Add service account status column to list view
- Add service account status filter to list view
- Include social auth user IDs in the search fields
- Add date hierarchy based on join date to list view
- Add team memberships inline
- Add community memberships inline
- Add social auths inline
- Add user settings inline
> Admin: Override the default user admin pages

- django/thunderstore/repository/admin/package.py
Make the recently introduced file_tree field in the PackageVersion model read only in its inline on the PackageAdmin page.
> Make file_tree read only in PackageVersionInline

- django/thunderstore/core/settings.py
Swap the django-cachalot config to work on an opt-out basis rather than opt-in, as it's the less harmful default in most cases and most db tables should be included.
Additionally, make the cache timeout configurable via environment variables.
> Update django-cachalot config

- django/thunderstore/social/api/experimental/views/complete_login.py
- django/thunderstore/social/api/experimental/views/overwolf.py
A few API views declared a serializer they supposedly used for the docs without actually using said serializer to format the data. This commit actually passes the data through the declared serialiers, which is generally what you'd expect when working on a DRF API.
> Actually use API serializers

- .github/workflows/deploy.yml
Remove a filter condition from the deploy job which prevented it from ever being run.
> Remove bad job filter from deploy workflow

- django/thunderstore/api/cyberstorm/tests/test_team.py
- django/thunderstore/api/cyberstorm/views/team.py
Cyberstorm API: add tests for sorting team-related list views
Refs TS-1856
Cyberstorm API: use StrictOrderingFilter on team-related list views
Based on non-blocking review comment, Mythic has apparently had some
issues with DRF's stock OrderingFilter, so use the home brewed
StrictOrderingFilter instead.
Refs TS-1856
> Cyberstorm API: improve sorting on team-related list views

- django/thunderstore/api/cyberstorm/serializers/__init__.py
- django/thunderstore/api/cyberstorm/serializers/community.py
- django/thunderstore/api/cyberstorm/tests/test_community_detail.py
- django/thunderstore/api/cyberstorm/tests/test_community_filters.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/community_filters.py
- django/thunderstore/api/urls.py
Cyperstorm API: remove package categories from CommunityDetail endpoint
Package categories and sections will be provided by a separate endpoint
in the future.
Refs TS-1885
Cyberstorm API: add CommunityFilters endpoint
The endpoint returns the community specific information that can be
used to filters packages, namely the available categories and sections.
Refs TS-1885
> Cyberstorm API: add CommunityFilters endpoint

- django/thunderstore/api/cyberstorm/serializers/team.py
- django/thunderstore/social/api/experimental/views/current_user.py
- django/thunderstore/social/tests/test_utils.py
- django/thunderstore/social/utils.py
Add support for avatars when using Discord as an OAuth provider
Unlike other providers, Discord doesn't provide an URL for the user
avatar straight up. Instead, we need to parse it from other data they
do provide.
Refs TS-1884
DRY up avatar fetching code
- Split the util function for reading the avatar into two: one that
accepts the User object and nondeterministically returns any one of
their avatars, and another that accepts SocialAuth object and returns
the avatar associated with that OAuth provider
- Use the latter when resolving the avatars of the currently
authenticated user
Refs TS-1884
> Add support for avatars when using Discord as an OAuth provider

- docker-compose.yml
Update the endpoint used for pre-signed s3 upload URLs by the development environment.
This update is necessary to enable proper integration testing with some of the frontend code that's in development. See https://github.com/thunderstore-io/thunderstore-ui/commit/bb2fc1ce857a512672496b9272acd0b010250101#diff-3c4dbbc0689a6ed61e26d415987d64eb05067e938423b6e3aa997b0e96bb49d5R79-R84 for more details
> Update dev env usermedia signing URL

- django/thunderstore/api/cyberstorm/serializers/community.py
- django/thunderstore/api/cyberstorm/tests/test_community_filters.py
Slugs of PackageCategory and PackageListingSections are unique only in
a scope of each Community. Send the globally unique ids to client so
they can be used when the client sends a package list filtering request
back to backend.
Refs TS-1890
> Cyberstorm API: return unique ids for category and section filters

- django/thunderstore/api/cyberstorm/serializers/community.py
- django/thunderstore/api/cyberstorm/tests/test_community_filters.py
- django/thunderstore/api/cyberstorm/tests/test_packages.py
- django/thunderstore/api/cyberstorm/views/packages.py
Ids should be provided as strings when the client requests a list of
community's package categories to be used as filters for package
listings. Received ids should be treated as strings when client
requests a filtered package listing.
Refs TS-1899
> Cyberstorm API: treat PackageCategory ids as strings

- django/thunderstore/api/cyberstorm/views/packages.py
- remove unnecessary definition of get method
- in filter_queryset, use the queryset passed as a parameter rather
than refetch in unnecessarily
- in filter_queryset, avoid overriding the queryset received as a
parameter, although DRF's implementation actually does that
Refs TS-1875
> Cyberstorm API: minor improvements to BasePackageListAPIView

- django/thunderstore/api/cyberstorm/tests/test_packages.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/packages.py
- django/thunderstore/api/urls.py
Endpoint for fetching listed packages that depend on a given package.
To be included in the results the packages must also be listed in the
requested community.
Refs TS-1975
> Cyberstorm API: add package dependant list endpoint

- django/thunderstore/core/settings.py
- django/thunderstore/repository/tasks/caches.py
- docker-compose.yml
Add a dedicated task queue for long running tasks and increase the timeout of the API index building task
> Add a task queue for long running tasks

- django/thunderstore/community/tests/test_package_listing.py
Fix package listing unit tests
- Copy-pasted test case name caused one of the tests not getting run
- Once the test was run, it failed. Test case was fixed to match the
current implementation, altough I'm not 100% certain it mathches the
intent of the property being tested
> Fix package listing unit tests

- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/repository/cache.py
Add filter_by_community_approval_rule for PackageListing QuerySet
Filter the QuerySet by approval status, taking into account whether the
Community has approval process activated.
Refs TS-1980
> Add filter_by_community_approval_rule for PackageListing QuerySet

- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package_version.py
Implement PackageVersionManager as QuerySet and add listed_in filter
Define Manager as a QuerySet to make the methods chainable by default.
Add a new method for filtering PackageVersions by the Community where
the related package is listed.
Refs TS-1980
> Implement PackageVersionManager as QuerySet and add listed_in filter

- django/thunderstore/repository/api/experimental/tests/test_package_index.py
- django/thunderstore/repository/api/experimental/views/package_index.py
Reduce the amount of queries executed when building the new package index by prefetching related objects. In exchange, this increases the memory consumption.
> Reduce package index building query usage

- builder/src/upload.tsx
- django/thunderstore/repository/templates/repository/package_create_old.html
Add a note about how the team a package is uploaded to becomes a part of the package ID.
This is something that has (understandably) caused confusion to new users and led to requests to remove packages uploaded under team names that weren't intended to be included in the package ID.
> Add note about team name usage as namespace

- django/thunderstore/core/settings.py
Configure the blob storage to also use the mirrored storage backend as it was mistakenly not using it yet
> Configure blob storage to use the mirrored storage

- django/docker_entrypoint.py
Add support for configuring max simultaneous connection count per gunicorn worker with the GUNICORN_WORKER_CONNECTIONS environment variable.
> Add GUNICORN_WORKER_CONNECTIONS config option

- django/thunderstore/api/cyberstorm/tests/test_package_details.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/package_detail.py
- django/thunderstore/api/urls.py
Endpoint for fetching the information required to display a package
view. Markdown content is not included since it will be read from a
separate endpoint that processes the raw data to markup in a safe
manner. Also content under different tabs is omitted since they will
be loaded separately when needed.
When the implementation was nearly complete, it occured to us that
we'll actually need a similar endpoint for each versions, whereas the
current implementation assumes the latest version is always requested.
Rather than make this a blocker now, it was decided to move on with the
current implementation and refactor it in the future as needed.
Refs TS-1980
> Cyberstorm API: add package details endpoint

- django/thunderstore/api/cyberstorm/tests/test_markdown.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/markdown.py
- django/thunderstore/api/urls.py
The endpoints return the markdown prerendered to HTML.
Refs TS-2000
> Cyberstorm API: add endpoint for package's README and CHANGELOG

- django/thunderstore/repository/api/experimental/serializers/main.py
Disable download & rating metrics from the experimental API, as it was returning invalid data.
The disabling is done by setting the returned values to -1, which keeps the endpoint backwards-compatible while also clearly indicating that the value is not usable.
> Disable package metrics from the experimental API

- django/thunderstore/repository/views/repository.py
Change the wording used in the dependants link to refer to packages instead of mods.
This change is done based on a recent discussion in the Lethal Company community, where it became apparent that using 'Mods' was setting up users with false expectations, as all kinds of packages are included in the number (such as modpacks).
While this doesn't solve the use case of "I want to see how many other mod developers integrate with my mod" (which seemed to be the main use case), it should at least be a minor improvement over the previous wording.
> Update dependants link wording

- django/thunderstore/core/tests/test_storage.py
Evidently some configurations of test run splitting will lead to a problem where a test starts off expecting a file to not exist in an S3 bucket, but it does. This problem does not occur if all tests are run.
This does not solve the root cause, but it does address the issue for the specific test which was failing.
> Fix odd issue with test state consistency

- django/thunderstore/api/cyberstorm/tests/test_package_details.py
- django/thunderstore/api/cyberstorm/views/package_detail.py
The field works on the database level a bit differently than the other
fields in that it allows empty values to be stored as empty strings
rather than nulls.
Hide this implementation detail and keep the API consistent by
returning None if the field is in fact empty.
Refs TS-1980
> Cyberstorm API: return empty PackageVersion.website_url as None

- django/thunderstore/api/cyberstorm/views/package_detail.py
This protects the API from breaking if __str__ is changed in the future
and generally makes it easier to see where __str__ is used.
Refs TS-2005
> Map serializer to object property rather than __str__

- django/thunderstore/repository/views/repository.py
Improve the package management panel visibility check to account for partial management permissions rather than only showing it for users with access to manage the global Package model's deprecation.
> Show management panel to community moderators

- django/thunderstore/repository/models/package.py
- django/thunderstore/repository/tests/test_package.py
Adjust the upload processing behavior to not implicitly remove existing categories from packages when a new version is uploaded. Many users re-select some categories when updating their package without realizing that any category _not_ selected gets removed.
This commit changes the behavior so that category removals will never happen when mods are updated, which should reduce the amount of accidental category removals.
Categories can still be removed via the package management panel.
> Stop implicit removal of categories

- django/thunderstore/community/admin/community.py
Set the recently introduced aggregated_fields as read-only on the Community model admin page.
> Set Community.aggregated_fields as readonly

- django/thunderstore/community/models/package_listing.py
- django/thunderstore/webhooks/audit.py
- django/thunderstore/webhooks/models/audit.py
Make the user field in audit events optional for logs produced by system
events.
> Make audit event user optional for system logs

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
To avoid slowdowns, PackageListingAPIView returns only up to four
dependencies. To compensate, the number of total dependencies is
returned in a separate field.
An endpoint for returning all the dependencies in a paginated manner
will be added later.
Refs TS-2012
> Cyberstorm API: limit the number of returned package dependencies

- builder/src/api/api.ts
- builder/src/components/PackageReview/Context.tsx
- builder/src/components/PackageReview/Modal.tsx
- builder/src/components/PackageReview/useForm.ts
- django/thunderstore/community/api/experimental/tests/test_api_approval_status.py
- django/thunderstore/community/api/experimental/views/listing.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/templates/community/packagelisting_detail.html
- django/thunderstore/repository/views/repository.py
Add a link to the Thunderstore Discord on the package rejection message as a means of contacting moderators for clarification on rejections.
Additionally include a moderator-only panel for internal notes and make it possible to include them when approving or rejecting packages.
> Improve package review tool & status messages

- builder/src/scss/navbar.scss
- django/thunderstore/frontend/templates/base.html
Increase the community selection dropdown to 4 columns as it no longer fits new communities.
Hopefully we'll get the community list page ready before this becomes a problem again.
> Increase the community dropdown size to 4 columns

- django/thunderstore/repository/package_upload.py
- django/thunderstore/repository/validation/tests/test_zip.py
- django/thunderstore/repository/validation/zip.py
Include validation that ensures the zip file starts at offset 0 and that it includes no relative paths in the files.
In theory the zip files might still contain bogus data in the middle, but this is fairly unlikely to happen in practice and shouldn't impact the behavior of other applications.
> Bolster zip file validation

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package_version.py
Add PackageVersion.is_effectively_active
Helper method checks that both the PackageVersion and the related
Package are active. This is acts as a pair for the existing
Package.is_effectively_active helper.
Refs TS-2013
Cyberstorm API: include deactived dependencies for package listing
Even if a dependency is deactived, it's still a dependency of the
package, which might not work without it. To avoid misleading
information on the website, include deactived dependencies too.
PackageVersion is considered deactived if the parent Package is
deactived, even if the specific version would be active.
Annotating the "effective active status" to the QuerySet was
considered, but since the related package is prefetched for other
purposes anyway, it seemed like an unnecessary step.
Refs TS-2013 …
> Cyberstorm: show deprecated package dependencies

- django/thunderstore/frontend/templates/base.html
Makes the header do this:
-----
> Make community discord link title unambiguous

- django/thunderstore/repository/api/v1/tests/test_metrics.py
- django/thunderstore/repository/api/v1/views/metrics.py
Expose the latest package version number on the package metrics API. The main goal is to provide a future-proof way of integrating to this information, given that the current v1 API has no reasonable way of accessing it directly.
Resolves #970
> Expose latest package version number via v1 API

- django/thunderstore/repository/tests/test_tabs_mixin.py
- django/thunderstore/repository/views/mixins.py
- django/thunderstore/repository/views/package/detail.py
- django/thunderstore/repository/views/wiki.py
Implement a package listing detail view which takes care of commonly used functionality such as permission checks and tab context for the package detail views. This makes it easier to add more tabs in the future.
**MERGE #991 FIRST**
> Add a package listing detail view

- django/thunderstore/cache/utils.py
- django/thunderstore/core/management/commands/clear_cache.py
- django/thunderstore/core/settings.py
- django/thunderstore/core/tests/test_celery.py
- django/thunderstore/modpacks/models/legacyprofile.py
- django/thunderstore/modpacks/tests/test_legacyprofile.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tasks/__init__.py
- django/thunderstore/repository/tasks/downloads.py
- django/thunderstore/repository/tests/test_download_metrics.py
- django/thunderstore/repository/views/package/download.py
- docker-compose.yml
This PR contains caching for the download URL endpoint and profile storage size check. Additionally, the download log has been moved to a background task as to not block request processing unnecessarily long.
Finally, the management command for clearing caches was updated to support selecting which cache(s) to clear.
> Several cache improvements

- django/thunderstore/repository/admin/package.py
Make the "visibility" field read-only in the PackageVersionInline on Package detail admin page.
> Make visibility read-only in PackageVersionInline

- django/thunderstore/core/settings.py
Make it possible to enable or disable storage mirroring depending on the storage use case via environment variables.
> Add granular config options for storage mirroring

- django/thunderstore/social/api/experimental/views/complete_login.py
- django/thunderstore/social/tests/test_complete_login.py
The old implementation prevented creation of upper case versions of existing usernames, but didn't prevent creation of lower case version of existing uppercase usernames.
> Prevent creation of lower case versions of existing usernames

- builder/src/retry.ts
- builder/src/state/FileUpload.ts
- builder/src/throttle.ts
Implement automatic retrying for failed file part upload attempts and limit the maximum parallelism to 3 instead of attempting to upload all parts in parallel.
This should significantly improve the experience for uploaders of large files on slower connections without degrading performance on faster connection speeds. The assumption is that limiting the parallelism should promote actually completing file parts as individual parts no longer compete on bandwidth with each other as much, and automatic retries should make the uploader more robust for failures overall.
> Implement retries and max parallelism to uploads

- .env.template
Replaced URL for .env.template's DECOMPILER_API_HOST so that decompiler functions correctly
> Update .env.template DECOMPILER_API_HOST

- django/thunderstore/repository/api/v1/tests/test_metrics.py
- django/thunderstore/repository/api/v1/urls.py
- django/thunderstore/repository/api/v1/views/deprecate.py
- django/thunderstore/repository/tests/test_bot_api.py
- django/thunderstore/repository/urls.py
Aimed to replace #951:
- Rebase to current HEAD of master branch
- After rebase, all that's left of the first commit is [a single line change to test case](https://github.com/thunderstore-io/Thunderstore/commit/a7e45a9208cea265f9c78de7b22d3231ce10941b#diff-d9f69ab2e04c0994729fcac1a309dc2acf7a04591afcd84bb584a04c052fc2c5R41)
- The second commit remains unchanged
- Introduce a third commit which adjusts unit tests to not test the dropped redundant endpoints
> Reduce noice in v1 API URLs (rebased)

- builder/src/scss/base.scss
- builder/src/scss/general.scss
- django/thunderstore/repository/templates/repository/includes/dependencies.html
This would resolve the underlying issue https://github.com/thunderstore-io/Thunderstore/pull/1040 seeks to fix.
Also changes the color-scheme to dark which means scroll bars will be dark (which scrollable elements inside the page need to not look terrible).
> Set maximum height, add scrolling to dependency list on Package Details page

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
Update calls to `docker-compose` to use the new calling convention of `docker compose` across the repository.
> Update docker-compose calling convention

- django/thunderstore/core/management/commands/content/base.py
- django/thunderstore/core/management/commands/content/package_version.py
- django/thunderstore/core/management/commands/create_test_data.py
- django/thunderstore/core/tests/test_management_commands.py
Reusing the same image means we don't need to upload so many images to S3 bucket (or multiple buckets if mirrors are configured), significantly speeding up creating larger data sets.
The implementation reuses the path of the first created image, which uses the team-package-version naming pattern, instead of using something more descriptive like "default.png". Bypassing the generated name would have required hacky stuff for the function that calculates the value for ImageField's upload_to attribute, or the models save method. As this would make it theoretically possible to things go wrong in the production, it was deemed better to just use the misleading image name in test environments.
> Add option to reuse PackageVersion icon on test data creation

- builder/src/scss/navbar.scss
- django/thunderstore/community/templates/community/community_list.html
- django/thunderstore/community/tests/test_views.py
- django/thunderstore/community/views.py
- django/thunderstore/core/urls.py
- django/thunderstore/frontend/templates/base.html
Implement a simple community list view, intended to serve as a fallback for environments where the cyberstorm remix frontend isn't running (such as local development environments)
Remove the "other communities" section from the navbar communities dropdown and instead link to the community list page.
Sample:
> Add community list view

- django/thunderstore/community/templates/community/community_list.html
The community list template was expecting a context variable called page_title to be used for rendering the page title even though the view using the template doesn't populate such a variable.
Replace the variable usage with a constant value in the template directly.
> Fix community list template title

- django/thunderstore/repository/admin/package.py
- django/thunderstore/repository/admin/package_version.py
Disable searching on file checksums from the package & package version admin list views as the queries take too long to run against the production dataset.
> Disable checksum search from package admin list

- django/thunderstore/repository/api/v1/views/listing_index.py
Calls to the API endpoint can indicate that a mirror CDN is preferred by including a query parameter in the request. The endpoint will return an URL to the preferred CDN only if the CDN is allowlisted in the config.
This feature is intended to mitigate the issues of the CDN provider.
> Support mirror CDNs for chunked package list index download

- django/thunderstore/community/admin/package_listing.py
Disable searching on file checksums from the package listing admin list view as the queries take too long to run against the production dataset.
This is nearly identical to https://github.com/thunderstore-io/Thunderstore/pull/1057 just for the Package Listing admin.
This functionality remains in the data blob reference admin.
> Disable checksum search from listing admin list

- .github/workflows/test.yml
Pin the version to 1.4.1. This ought to fix the broken poetry install issue, similar to the issue in the thunderstore-ui project.
Refs. TS-2274
> Pin snok/install-poetry version (TS-2274)

- django/thunderstore/community/models/community.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_community_aggregated_fields.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/frontend/api/experimental/tests/test_frontpage.py
Develop a new function to filter `PackageListing` objects that are uniquely associated with a single community. This functionality is useful for aggregating results from a specific community while excluding packages shared across multiple communities. By doing so, it ensures that aggregated download and package counts provide accurate information, avoiding inflation caused by multi-community listings.
Additionally, this pull request (PR) includes two new tests and updates to existing ones to validate the functionality of the newly added filter.
> Exclude multi community packages (TS-2265)

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/repository/models/package.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package.py
- django/thunderstore/repository/tests/test_package_version.py
- Added an is_removed property to the Package and PackageVersion models to determine whether the respective packages and package versions are marked as removed.
- Included the is_removed field in the DependencySerializer.
- Implemented corresponding unit tests.
> Add is removed status (TS-2275)

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/repository/models/team.py
Modify the cyberstorm package listing API to only render public team members in the team details. Currently there is no way to mark a team membership as public, so an empty set is always returned.
> Cyberstorm API: Only render public team members

- django/thunderstore/social/api/experimental/views/current_user.py
- django/thunderstore/social/api/v1/views/current_user.py
- django/thunderstore/social/tests/test_current_user.py
Added is_staff field to the payload of /api/experimental/current-user/ and /api/v1/current-user/info/. The field returns true or false if the user is authenticated, and null if the user is not authenticated.
Refs. TS-2283
> Add is_staff to two endpoints (TS-2283)

- django/thunderstore/api/cyberstorm/tests/test_package_deprecate.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/package_deprecate.py
- django/thunderstore/api/urls.py
A new view and serializer were added to the Cyberstorm API to handle package deprecation. The endpoint requires user authentication and proper permissions to manage deprecations. It leverages existing `deprecate` and `undeprecate` functions from the `Package` model. Additionally, tests were implemented to verify functionality.
>  Cyberstorm deprecate package endpoint (TS-2296)

- django/conftest.py
- django/thunderstore/api/cyberstorm/serializers/__init__.py
- django/thunderstore/api/cyberstorm/serializers/package.py
- django/thunderstore/api/cyberstorm/tests/test_package_permissions.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/package_permissions.py
- django/thunderstore/api/urls.py
- django/thunderstore/repository/tests/test_package_detail_view.py
- django/thunderstore/repository/tests/test_permissions_checker.py
- django/thunderstore/repository/views/package/detail.py
- A new `PermissionsChecker` class has been created to centralize the logic for handling permission checks. Previously, permission checks were implemented in the PackageDetailView. The logic has now been moved to `PermissionsChecker`.
- The PackageDetailView has been updated to use PermissionsChecker.
- Tests for the PackageDetailView have been implemented to ensure that the transition to using the PermissionsChecker class has not introduced any errors.
- Dedicated tests have been written for the PermissionsChecker class.
- A new API endpoint has been implemented to allow users to retrieve the permissions they have for a specific package. The current user is implicitly determined from the request, so the endpoint automatically applies the correct user context.
- A serializer has been …
> Moderation permissions via api (TS-2284)

- django/thunderstore/api/cyberstorm/tests/test_disband_team.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/team.py
- django/thunderstore/api/urls.py
Implement a DELETE endpoint for disbanding(deleting) teams in the Cyberstorm API.
Refs. TS-2313
> Implement cyberstorm disband team endpoint (TS-2313)

- django/thunderstore/api/cyberstorm/serializers/__init__.py
- django/thunderstore/api/cyberstorm/serializers/team.py
- django/thunderstore/api/cyberstorm/tests/test_create_team.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/team.py
- django/thunderstore/api/urls.py
- Implemented CyberstormCreateTeamSerializer
- Added validation for the name field.
- Ensured service accounts cannot create teams.
- Moved serializers from the team views file to the serializers file.
- Implemented TeamCreateAPIView for handling new team creation in the Cyberstorm API.
> Cyberstorm api create team (TS-2312)

- django/thunderstore/api/cyberstorm/serializers/package_listing.py
- django/thunderstore/api/cyberstorm/tests/test_package_listing_actions.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/package_listing_actions.py
- django/thunderstore/api/urls.py
This PR introduces serializers and views in the Cyberstorm API for package listing actions: update categories, reject, and approve.
Changes Introduced:
- New serializers for package listing actions.
- New views implementing the actions: update categories, reject, and approve.
- Unit tests to validate the functionality.
- URL configuration updated to include the new views.
The code is based on the existing logic from the experimental API, but it has been heavily refactored. While the underlying functionality remains the same, the implementation is more cleaner.
> Package listing action views (TS-2297)

- django/thunderstore/community/templates/community/packagelisting_detail.html
Update styling for the "Manual Download" button to use a conditional check. If the listing can be installed with mod manager, and the "Install with mod manager" button is rendered, the styles remain the same as before. However, if the "Install with mod manager" button is not rendered, the "Manual Download" button will adjust to the same size as the "Support the creator" button for a more consistent layout.
Refs. TS-2367
> Fix Manual Download button styling (TS-2367)

- builder/src/upload.tsx
- django/thunderstore/social/api/experimental/views/current_user.py
Fixed incorrect logic in comparison in `upload.tsx` so the current community is always at the top of the communities selection box.
Added `order_by("id")` to `current-user`'s `get_teams()`.
> Fix upload page sorting [TS-2344] [TS-2345]

- django/thunderstore/api/cyberstorm/tests/test_package_listing_list.py
- django/thunderstore/api/cyberstorm/views/package_listing_list.py
Update the function to take community as an argument.
Update the query to user filter instead of the double negative exclude filtering. This query seemed to not exclude packages with a rejected listing if the packages were multi-community packages. It seems to not handle rejected listings explicitly for a given community, which returns unwanted results.
Refs. TS-2346
> Cyberstorm listing API filtering bug (TS-2346)

- builder/src/scss/general.scss
- builder/src/scss/theme/_variables.scss
See this banner in the Boneworks community?
- It's too hard to read
- I've already read it and I can't get rid of it
This PR changes the color of yellow to a darker shade of yellow and adds some css that isn't used anywhere, but could be used in dynamic HTML to let us make dismissible alerts:
If they're dismissible we can use them more liberally such as when a game updates to cut down on the amount of support people need.
> Add css for dismissible alerts

- django/thunderstore/api/cyberstorm/views/community_list.py
Increase page size from 150 to 300 since we have a total of 150 communities in thunderstore at the moment.
> Increase Community list api view page size (TS-2403)

- django/thunderstore/api/cyberstorm/serializers/team.py
- django/thunderstore/api/cyberstorm/services/team.py
- django/thunderstore/api/cyberstorm/tests/services/test_team_services.py
- django/thunderstore/api/cyberstorm/tests/test_create_team.py
- django/thunderstore/api/cyberstorm/tests/test_disband_team.py
- django/thunderstore/api/cyberstorm/tests/test_team.py
- django/thunderstore/api/cyberstorm/views/team.py
- django/thunderstore/api/error_messages.py
- django/thunderstore/api/urls.py
@Roffenlund I was reviewing the diff between the last tag and current master and spotted a few things I'd like to see changed. Changed a few smaller portions myself already (but did not test nor update tests in case those broke with them), but left a slightly larger change for you.
There's a code comment in the team API views explaining the situation, but the gist of it is we should consolidate all business logic actions to a single channel and avoid double-implementation. This primarily applies to the Team management API views, but I did consider how applicable it's to package listing API views also. In the latter case the situation could be better (we already have similar implementations in the code base), but given that a lot of the actual business logic is already handled elsewhere …
> Review comments and minor adjustments

- django/thunderstore/repository/admin/package.py
Modify PackageVersionInline admin to explicitly show fields rather than explicitly exclude, fixing a bug that caused these pages to load slowly in production.
> Package admin VersionInline fix

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/repository/models/package.py
Add version_count to package listing endpoint. Implement cached_property to Package model for getting versions count.
> Add version count to package listing endpoint(TS-2370)

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/repository/models/package.py
Add the version_count to the get_custom_package_listing queryset as an annotation instead of fetching the version_count from the model's property function.
Remove the version_count property function from the package model.
Update tests accordingly.
Refs. TS-2447
> Refactor version_count in package_listing view (TS-2447)

- .github/workflows/test.yml
Update the codecov CI action from v1 to v5. v1 has stopped working for tokenless coverage report uploads which should work again with v5
> Update codecov action

- django/thunderstore/core/urls.py
- django/thunderstore/repository/templates/settings/team_disband.html
Replace Mythic#0001 contact info from API docs and the disband team page with just a Discord link.
> Replace Mythic#0001 contact info

- .pre-commit-config.yaml
- django/thunderstore/api/cyberstorm/services/package.py
- django/thunderstore/api/cyberstorm/services/package_listing.py
- django/thunderstore/api/cyberstorm/services/team.py
- django/thunderstore/api/cyberstorm/tests/services/test_package_listing_services.py
- django/thunderstore/api/cyberstorm/tests/services/test_package_services.py
- django/thunderstore/api/cyberstorm/tests/test_create_team.py
- django/thunderstore/api/cyberstorm/tests/test_disband_team.py
- django/thunderstore/api/cyberstorm/tests/test_package_deprecate.py
- django/thunderstore/api/cyberstorm/tests/test_package_listing_actions.py
- django/thunderstore/api/cyberstorm/tests/test_package_rating.py
- django/thunderstore/api/cyberstorm/views/package_deprecate.py
- django/thunderstore/api/cyberstorm/views/package_listing_actions.py
- django/thunderstore/api/cyberstorm/views/package_rating.py
- django/thunderstore/community/api/experimental/tests/test_api_package_listing.py
- django/thunderstore/community/api/experimental/views/listing.py
- django/thunderstore/community/models/community.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/core/exception_handler.py
- django/thunderstore/core/exceptions.py
- django/thunderstore/permissions/utils.py
- django/thunderstore/repository/api/v1/viewsets.py
- django/thunderstore/repository/forms/team.py
- django/thunderstore/repository/models/team.py
- django/thunderstore/repository/package_manifest.py
Implement service layer functions for deprecate/undeprecate and rate packages. Implement service layer functions for updating categories, reject, and approve package listings.
Use these service layer functions in the cyberstorm api, experimental api, and the v1 api.
Implement tests.
> Service layer to existing cyberstorm views (TS-2429)

- django/thunderstore/api/cyberstorm/serializers/community.py
- django/thunderstore/api/cyberstorm/tests/test_community_list.py
- django/thunderstore/api/cyberstorm/views/community_list.py
Use the DRF `get_queryset` function to fetch the Community queryset with or without unlisted communities depending on a query parameter passed to the endpoint.
Refs. TS-2470
> Implement query parameter for CommunityAPIView (TS-2470)

- django/thunderstore/api/cyberstorm/tests/test_package_listing_list.py
- django/thunderstore/api/cyberstorm/views/package_listing_list.py
Refactor the endpoints in package_listing_list.py endpoints to use PackageListing model instead of Package model. This simplifies the queries and filters a lot when using the PackageListing directly instead of doing a lot of backwards lookups from Package.
> Refactor package listing endpoints (TS-2349)

- django/thunderstore/api/cyberstorm/views/community_list.py
Preserve filtering/search when include_unlisted=true in CommunityListAPIView.
Refs. None
> Fix how queryset is fetched in CommunityListAPI

- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/repository/models/package.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package.py
- django/thunderstore/repository/tests/test_package_version.py
Deactivate the visibility system's update logic, as it's currently not used for anything but ran into crashes in production.
> Deactivate visibility system update logic

- django/thunderstore/api/cyberstorm/tests/test_package_listing.py
- django/thunderstore/api/cyberstorm/views/package_listing.py
- django/thunderstore/community/models/package_listing.py
- django/thunderstore/community/tests/test_package_listing.py
- django/thunderstore/repository/models/package.py
- django/thunderstore/repository/models/package_version.py
- django/thunderstore/repository/tests/test_package.py
- django/thunderstore/repository/tests/test_package_version.py
Add a new is_unavailable status to the Package and PackageVersion
models to determine whether a package or package version is unavailable.
A package is considered unavailable if there is no PackageListing
object linking the package to the currently viewed community.
Even if a PackageListing object exists linking the package to the
community, its status might be "rejected," which would render the
package unavailable.
> Add unavailable status (TS-2276)

- django/thunderstore/markdown/allowed_tags.py
Add the 'open' attribute to the 'details' so it will be recognized by the markdown renderer.
Refs. TS-2545
> Add attribute to allowed_attributes (TS-2545)

- builder/src/components/DragDropFileInput.tsx
- builder/src/upload.tsx
- builder/src/uploadZipValidation.ts
- builder/src/vendor/zip-fs-full.d.ts
Prevents users from attempting to upload packages that aren't zips or packages without a manifest, icon, and readme in the root of the zip.
Warns the user when uploading packages with > 8 DLL files, an Assembly-CSharp.dll file, or BepInEx.dll.
Fixes a chromium bug preventing the selection of a file that was previously selected and canceled.
> Add Client-Side Pre-Upload Package Validation

- django/thunderstore/core/exception_handler.py
- django/thunderstore/core/tests/test_api_exceptions.py
Add a standard DRF response with a 500 status code when we encounter an unexpected error in out custom exception handler. Implement tests for the expected errors in the exception handler.
> DRF unhandled exceptions (TS-2459)

- django/thunderstore/api/cyberstorm/serializers/__init__.py
- django/thunderstore/api/cyberstorm/serializers/team.py
- django/thunderstore/api/cyberstorm/services/team.py
- django/thunderstore/api/cyberstorm/tests/services/test_team_services.py
- django/thunderstore/api/cyberstorm/tests/test_endpoints.py
- django/thunderstore/api/cyberstorm/tests/test_team.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/team.py
- django/thunderstore/api/urls.py
- django/thunderstore/repository/forms/team.py
- django/thunderstore/repository/tests/test_team_forms.py
- django/thunderstore/repository/tests/test_views.py
- django/thunderstore/repository/views/team_settings.py
* Implement and endpoint in cyberstorm api for updating teams
* Support only updating donation_link for now
* Implement tests
* Implement service layer function for updating teams, and implement tests
* Use the service layer function in the form view responsible for updating team donation links
> Implement update team endpoint (TS-2314)

- django/thunderstore/api/cyberstorm/tests/endpoint_data.py
- django/thunderstore/api/cyberstorm/tests/test_package_listing_actions.py
- django/thunderstore/api/cyberstorm/views/__init__.py
- django/thunderstore/api/cyberstorm/views/package_listing_actions.py
- django/thunderstore/api/urls.py
Implement view, URL and tests for reporting packages. Utilize existing service layer function and serializer used in the Experimental API.
> Cyberstorm api report package (TS-2638)

- django/thunderstore/api/cyberstorm/serializers/package.py
- django/thunderstore/api/cyberstorm/tests/test_package_version_list.py
- django/thunderstore/api/cyberstorm/tests/test_query_count.py
- django/thunderstore/api/cyberstorm/views/package_version_list.py
Annotate the queryset with active_package_versions instead of calling PackageVersion.is_removed, which avoids triggering an N+1 query.
Refs. TS-2672
> Optimize dependencies list queryset query (TS-2672)
